remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
title: "Matrixx"
description: "A custom ROM based on crDroid Android with extra pinch of salt"
relative_links:
  enabled: true
  collections: true
includes:
  - changelog.html
  - devices.html
